############################################################################################
######################################## server ############################################
############################################################################################
server:
  port: 8761
############################################################################################
######################################## spring ############################################
############################################################################################  
spring:
  application:
    name: eureka-server
############################################################################################
########################################## 认证 ##############################################
############################################################################################
  security:
    user:
      name: admin
      password: 123456
############################################################################################
######################################## eureka ############################################
############################################################################################
eureka:
  client:
    # 是否要注册到其他Eureka Server实例
    register-with-eureka: false
    # 是否要从其他Eureka Server实例获取数据
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:${server.port}/eureka/